version: 2

sources:
  - name: stitch_google_ads
    schema: "{{ var('stg_google_ads_stitch_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _sdc_batched_at

    tables:
      - name: "CAMPAIGN_PERFORMANCE_REPORT"
      - name: campaigns
      - name: ad_groups
      - name: ads
      - name: "AD_PERFORMANCE_REPORT"

  - name: segment_google_ads
    schema: "{{ var('stg_google_ads_segment_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: uuid_ts

    tables:
      - name: campaign_performance_reports
      - name: campaigns
      - name: ad_performance_reports
      - name: ad_groups
      - name: ads
